---
repo_name: "comedylib"
repo_root: "/var/www/{{ repo_name }}"
repo_url: "ssh://hg@bitbucket.org/lucianu/comedylib"
repo_host: "bitbucket.org"

app_user: "{{ repo_name }}"
app_group: "{{ app_user }}"
deployment_user: lucian
remote_user: "{{ deployment_user }}"
domain_name: "comedylib.com"

virtualenvs_path: "{{ repo_root | dirname }}/.virtualenvs"
project_venv_path: "{{ virtualenvs_path }}/{{ repo_name }}"
project_venv_bin_path: "{{ project_venv_path }}/bin"
project_run_path: "/var/www/run"
project_log_path: "/var/www/log"

# Aliases for ansible-uwsgi
site_app_user: "{{ app_user }}"
site_repo_name: "{{ repo_name }}"
site_repo_root: "{{ repo_root }}"

uwsgi_app_name: "{{ repo_name }}"
uwsgi_django_settings: "{{ django_settings_file }}"
uwsgi_module: "{{ repo_name }}.wsgi"
uwsgi_venv: "{{ project_venv_path }}"

celery_app: "{{ repo_name }}.celery.config"
celery_virtualenv: "{{ project_venv_path }}"
celery_work_dir: "{{ repo_root }}"

configs_root: "/usr/local/etc"
newrelic_config_file: "{{ configs_root }}/newrelic/{{ repo_name }}/newrelic.ini"
site_log_dir: "/var/log/{{ repo_name }}"

system_packages:
  - build-essential
  - git
  - liblcms1-dev
  - libfreetype6-dev
  - libjpeg8-dev
  - zlib1g-dev
  - libxml2-dev
  - libxslt1-dev
  - mercurial
  - python-dev
  - python-pip
  - python-psycopg2
  - rabbitmq-server
