---
- name: install nginx
  apt: name=nginx update_cache={{ update_apt_cache }} state=installed
  sudo: yes
  tags: packages

- name: create the nginx configuration file
  template: src=nginx_conf.j2
            dest=/etc/nginx/sites-available/{{ repo_name }}
            backup=yes
  sudo: yes
  notify:
    - restart nginx

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default
        state=absent
  sudo: yes
  notify:
    - restart nginx

- name: enable application site
  file: src=/etc/nginx/sites-available/{{ repo_name }}
        dest=/etc/nginx/sites-enabled/{{ repo_name }}
        state=link
  sudo: yes
  notify:
    - restart nginx
