---
- name: install solr-jetty
  apt: name=solr-jetty state=present update_cache=yes
  sudo: yes

- name: copy over the jetty config
  copy: src=jetty
        dest=/etc/default/jetty
  notify:
    - restart jetty
  sudo: yes

- name: copy over schema.xml
  copy: src=schema.xml
        dest=/etc/solr/conf
  notify:
    - restart jetty
  sudo: yes
